# Generated by Django 5.0.7 on 2024-07-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cusine',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Thai', 'Thai'), ('Chinese', 'Chinese'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
