# Generated by Django 5.0.7 on 2024-07-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_cusine'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
